### ISSUE TITLE
Android Ascet-configurator Translation

### ISSUE THREAD

**Issue by gamecompiler** [PingvinOpenTag/LTAscetic#9]
Hi, id used the Ascet-configurator (Android) today.
Please please translate it in English Oo! 
And some things are displayed wrong on my phone.

![screenshot_2016-01-02-22-18-00](https://cloud.githubusercontent.com/assets/7261213/12076129/3f9c7e04-b19f-11e5-9fda-a277ebf61cf2.jpeg)
![screenshot_2016-01-02-22-18-10](https://cloud.githubusercontent.com/assets/7261213/12076128/3f9bf04c-b19f-11e5-80ff-17701330f4b6.jpeg)

**Comment by gamecompiler** [comment]
Id started the translation already, but what means:
Скрыть служебные поля
Считать настройки

And id translated the second tab as preferences, where im able to upload, download preferences to device. And the last one as remote, where i can enter commands (?).

**Comment by gamecompiler** [comment]
What is the baudrate to talk to the weapon ?
I got a message "Ascet 3.1" and nothing more....

Thanks in advance

**Comment by PingvinOpenTag** [comment]
Well, I'll transfer. Module using the remote control is not implemented.

To read the settings from a device in the "Protocol" ("Протокол") you have to press the button "Read from the device" ("Считать из устройства") 
https://www.youtube.com/watch?v=n5ikXYz3mhE

**Comment by PingvinOpenTag** [comment]
Can i configure if a bluetooth bandana is used (Master/Slave) ?
Do i have to configure if keys are used ?
--------------------------------------------------------------------
Bandana - Master
Tag - Slave
Bluetooth modules are configured using the AT-commands
armada.ltascet.com/images/hc-05.pdf
http://armada.ltascet.com/index.php/ru/tekhnologii-v-menu/asket/moduli-rasshireniya-dlya-asketa/blyutus-modul/nastrojka-bluetooth-modulej

**Comment by PingvinOpenTag** [comment]
I recommend to the bandana printed circuit board powered from 3V. Then bluetooth shield is not needed. 
http://www.youtube.com/watch?v=OKqPU76Skjw

**Comment by PingvinOpenTag** [comment]
Configurator will rewrite on QML (change the interface). Qt widgets not useful on small screens of mobile devices.

**Comment by gamecompiler** [comment]
Ok, now im confused, to get it run, what i have to do ? I have two setuped weapons.
Cant you add a config.h file where im able to define if a bluetooth module, LCD e.t.c is connected or not ?

I do not understand how i do change the firmware. Id hoped that im able to do that in the configurator....
I just want a gun with wired head sensor ....
I just want to play :cry: 

(Did you check the new part list ? Can´t await to build more of two)

**Comment by PingvinOpenTag** [comment]
Nothing needs to be configured. Everything works so. If you do not need the LCD or Bluetooth - simply do not connect them to the board.

If you want to play only with a wired bandana - through a resistor 10 to the connecting pin "Status"  (pin 2 on connector for Bluetooth Module) to the ground, otherwise the system will not work against cheating.

Initially firmware (or bootloader) can upload with the help of SPI programmer.
Be very careful with setting FUSES!!!

Programmers are different.
The easiest - it's  "LPT  5 wires"
http://armada.ltascet.com/index.php/ru/proshivka/kak-i-chem-proshit-asketa

I recommend using the USB programmers.
http://dvrobot.ru/var/cache/images/product/45/00/4500628ad509cd073e987c6ba312fd40-324.jpg
http://dvrobot.ru/237/213.html
The program is to work with this programmer.
http://yourdevice.net/proekty/avrdude-prog

Subject extensive, I recommend to you before programming device, available on the respective resources, how to program the AVR for SPI
And at first practice on the breadboard.
Because if you are, for example, incorrectly configured FUSE - programmer can no longer connect to the controller.

There resource project

There resource project
Help me to fill it with content.
What is your native language?
http://armada.ltascet.com

**Comment by gamecompiler** [comment]
Ok, can you resend me the login details ? 
My new e-mail address is justus (at) strongforce (DOT).de
my old still exists and i also read from this mail.

Thanks in advance.

**Comment by PingvinOpenTag** [comment]
Check Mail
